name: GTORoll
options:
  bundleIdPrefix: com.poshboy
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"

targets:
  GTORoll:
    type: application
    platform: iOS
    sources:
      - path: GTORoll
        createIntermediateGroups: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.poshboy.gtoroll
      INFOPLIST_GENERATION_MODE: GeneratedFile
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      
  GTORoll Watch App:
    type: application
    platform: watchOS
    sources:
      - path: GTORoll Watch App
        createIntermediateGroups: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.poshboy.gtoroll.watchkitapp
      INFOPLIST_GENERATION_MODE: GeneratedFile
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      SUPPORTS_WATCH_APP_RUNNING_WITHOUT_IOS_APP: YES
