name: GTORoll
options:
  bundleIdPrefix: com.poshboy
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"

targets:
  GTORoll:
    type: application
    platform: iOS
    sources:
      - path: GTORoll
        createIntermediateGroups: true
    info:
      path: GTORoll/Info.plist
      properties:
        CFBundleDisplayName: GTORoll
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        WKWatchAppBundleIdentifier: com.poshboy.gtoroll.watchkitapp
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.poshboy.gtoroll
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      
  GTORoll Watch App:
    type: application
    platform: watchOS
    sources:
      - path: GTORoll Watch App
        createIntermediateGroups: true
    info:
      path: GTORoll Watch App/Info.plist
      properties:
        CFBundleDisplayName: GTORoll
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        WKApplication: true
        WKCompanionAppBundleIdentifier: com.poshboy.gtoroll
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.poshboy.gtoroll.watchkitapp
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
