name: GTORoll
options:
  bundleIdPrefix: com.poshboy
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"

targets:
  GTORoll:
    type: application
    platform: iOS
    sources:
      - path: GTORoll
        createIntermediateGroups: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.poshboy.gtoroll
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      
  GTORoll Watch App:
    type: application
    platform: watchOS
    sources:
      - path: GTORoll Watch App
        createIntermediateGroups: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.poshboy.gtoroll.watchkitapp
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      WK_COMPANION_APP_BUNDLE_IDENTIFIER: com.poshboy.gtoroll
